### ISSUE TITLE
MFQE trained model?

### ISSUE THREAD

**Issue by dizcza** [ryanxingql/powervqe#1]
Thanks for putting the effort to standardize the framework.

I noticed you have already pushed code to [mfqev2 config](https://github.com/ryanxingql/powervqe/tree/main/mmediting/configs/restorers/mfqev2) to be used in mmediting. Are there trained models (`.pth`) I could use?

Thanks.

**Comment by ryanxingql** [comment]
Hi dizcza, thanks for your interest!
As indicated [here](https://github.com/ryanxingql/powervqe#6-test), the pre-trained models are released at the latest Releases [here](https://github.com/ryanxingql/powervqe/releases/tag/v1.0).

**Comment by dizcza** [comment]
I see, thanks.
