### ISSUE TITLE
STDF forward tensors size mismatch

### ISSUE THREAD

**Issue by dizcza** [ryanxingql/powervqe#2]
I copied the sources from the `mmediting` folder to the local `mmediting` folder from the official github repo, downloaded the stdf_ldv_v2.zip from the releases, ran the `restoration_video_demo.py`, and got the error:

```python
[/content/mmediting/mmedit/models/restorers/basic_restorer.py](https://localhost:8080/#) in forward(self, lq, gt, test_mode, **kwargs)
     73 
     74         if test_mode:
---> 75             return self.forward_test(lq, gt, **kwargs)
     76 
     77         return self.forward_train(lq, gt)

[/content/mmediting/mmedit/models/restorers/stdf.py](https://localhost:8080/#) in forward_test(self, lq, gt, meta, save_image, save_path, iteration)
     59             dict: Output results.
     60         """
---> 61         output = self.generator(lq)
     62         if self.test_cfg is not None and self.test_cfg.get('metrics', None):
     63             assert gt is not None, (

[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *input, **kwargs)
   1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110             return forward_call(*input, **kwargs)
   1111         # Do not call functions when jit is used
   1112         full_backward_hooks, non_full_backward_hooks = [], []

[/content/mmediting/mmedit/models/backbones/sr_backbones/stdf.py](https://localhost:8080/#) in forward(self, x)
    223             Tensor: Out center frame with shape (n, c, h, w).
    224         """
--> 225         out = self.stdf(x)
    226         out = self.qenet(out)
    227 

[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *input, **kwargs)
   1108         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110             return forward_call(*input, **kwargs)
   1111         # Do not call functions when jit is used
   1112         full_backward_hooks, non_full_backward_hooks = [], []

[/content/mmediting/mmedit/models/backbones/sr_backbones/stdf.py](https://localhost:8080/#) in forward(self, x)
    100             up_conv = getattr(self, 'up_conv{}'.format(i))
    101             print(i, out.shape, out_lst[i].shape)
--> 102             out = up_conv(torch.cat([out, out_lst[i]], 1))
    103 
    104         # compute offset and mask

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 136 but got size 135 for tensor number 1 in the list.
```

The `out.shape` is `torch.Size([1, 32, 136, 90])` while `out_lst[i].shape` is `torch.Size([1, 32, 135, 90])`.

I put `window_size=7` in the args to run the video restoration demo. And changed the config file and the model path, of course.

Using the latest mmcv, though I'm sure the error is in `sr_backbones/stdf.py`.

**Comment by ryanxingql** [comment]
Have you tried the test commands as indicated [here](https://github.com/ryanxingql/powervqe#6-test)?

And what is the resolution of your test input?

**Comment by dizcza** [comment]
I'm having another issue with that

```
$ !PORT=29510 ./tools/dist_test.sh ./configs/restorers/stdf/ldv_v2_4gpus.py ./stdf_ldv_v2/iter_1000000.pth 0 --save-path ./here

/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  FutureWarning,
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 225, in launch_agent
    master_port=master_port,
  File "<string>", line 15, in __init__
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/elastic/agent/server/api.py", line 87, in __post_init__
    assert self.local_world_size > 0
AssertionError
```

**Comment by dizcza** [comment]
> And what is the resolution of your test input?

The video frames are 360x540 (w x h).

**Comment by ryanxingql** [comment]
Try this:

```bash
conda activate open-mmlab
CUDA_VISIBLE_DEVICES=0 PORT=29510 ./tools/dist_test.sh ./configs/restorers/stdf/ldv_v2_4gpus.py ./stdf_ldv_v2/iter_1000000.pth 1 --save-path ./here
```

The gpu number should not be zero.

**Comment by dizcza** [comment]
```
  FutureWarning,
/content/mmediting/mmedit/utils/setup_env.py:33: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting OMP_NUM_THREADS environment variable for each process '
/content/mmediting/mmedit/utils/setup_env.py:43: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting MKL_NUM_THREADS environment variable for each process '
Traceback (most recent call last):
  File "./tools/test.py", line 142, in <module>
    main()
  File "./tools/test.py", line 91, in main
    data_loader = build_dataloader(dataset, **loader_cfg)
  File "/content/mmediting/mmedit/datasets/builder.py", line 134, in build_dataloader
    seed=seed)
  File "/content/mmediting/mmedit/datasets/samplers/distributed_sampler.py", line 46, in __init__
    'You may use too small dataset and our distributed '
ValueError: You may use too small dataset and our distributed sampler cannot pad your dataset correctly. We highly recommend you to use fewer GPUs to finish your work
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1913) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 718, in run
    )(*cmd_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./tools/test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-06-10_09:44:10
  host      : 5d19aebab58b
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1913)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

But I installed only
```
!pip3 install -qq openmim
!mim install mmcv-full
```
as typically in google colab pytorch and cudatoolkit is already there.

**Comment by dizcza** [comment]
You may try running the toolkit on colab to see the error.

----

> The gpu number should not be zero.

That is definitely something the pytorch dev should put in the assert description, not to mention the confusing naming convention for the cuda device id.

**Comment by ryanxingql** [comment]
> ```
>   FutureWarning,
> /content/mmediting/mmedit/utils/setup_env.py:33: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
>   f'Setting OMP_NUM_THREADS environment variable for each process '
> /content/mmediting/mmedit/utils/setup_env.py:43: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
>   f'Setting MKL_NUM_THREADS environment variable for each process '
> Traceback (most recent call last):
>   File "./tools/test.py", line 142, in <module>
>     main()
>   File "./tools/test.py", line 91, in main
>     data_loader = build_dataloader(dataset, **loader_cfg)
>   File "/content/mmediting/mmedit/datasets/builder.py", line 134, in build_dataloader
>     seed=seed)
>   File "/content/mmediting/mmedit/datasets/samplers/distributed_sampler.py", line 46, in __init__
>     'You may use too small dataset and our distributed '
> ValueError: You may use too small dataset and our distributed sampler cannot pad your dataset correctly. We highly recommend you to use fewer GPUs to finish your work
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1913) of binary: /usr/bin/python3
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 193, in <module>
>     main()
>   File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 189, in main
>     launch(args)
>   File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 174, in launch
>     run(args)
>   File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 718, in run
>     )(*cmd_args)
>   File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
>     failures=result.failures,
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ============================================================
> ./tools/test.py FAILED
> ------------------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> ------------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2022-06-10_09:44:10
>   host      : 5d19aebab58b
>   rank      : 0 (local_rank: 0)
>   exitcode  : 1 (pid: 1913)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ============================================================
> ```
> 
> But I installed only
> 
> ```
> !pip3 install -qq openmim
> !mim install mmcv-full
> ```
> 
> as typically in google colab pytorch and cudatoolkit is already there.

Please check your input data and make sure its layout is similar to this:

```text
powervqe/
`-- mmediting/
    `-- data/
        `-- mfqe_v2
            |-- test_gt/
            |   |-- BasketballDrill_832x480_500/
            |   |   |-- f001.png
            |   |   `-- ...
            |   `-- ...
            `-- test_lq/
```

**Comment by ryanxingql** [comment]
> You may try running the toolkit on colab to see the error.
> 
> > The gpu number should not be zero.
> 
> That is definitely something the pytorch dev should put in the assert description, not to mention the confusing naming convention for the cuda device id.

Thanks. Indeed, the `gpu number` is similar to `gpu index`. Sorry for that.

**Comment by dizcza** [comment]
> > You may try running the toolkit on colab to see the error.
> > > The gpu number should not be zero.
> > 
> > 
> > That is definitely something the pytorch dev should put in the assert description, not to mention the confusing naming convention for the cuda device id.
> 
> Thanks. Indeed, the `gpu number` is similar to `gpu index`. Sorry for that.

No, I meant the confusing part

```assert self.local_world_size > 0```

in the error description, and your hint about the GPU number made sense.

**Comment by ryanxingql** [comment]
Also, make sure you have changed the `data['test']['lq_folder']` and `data['test']['gt_folder']` in your config file.

**Comment by ryanxingql** [comment]
Feel free to open it if you have any questions.
