### ISSUE TITLE
关于指标结果的问题

### ISSUE THREAD

**Issue by woaicv** [ryanxingql/powervqe#3]
您好，非常感谢您的工作！我想请教下你们在竞赛里是在rgb上训练视频的吗？我看到您这边给的两个结果一个是Y-PSNR，一个是RGB-psnr（这个是mfqev2的测试集），这两个结果都是在rgb上训练然后在y或rgb通道上测的吗？为什么stdf的表现这么差，甚至都不如mfqev2（相比于之前在y通道训练 y通道测试）。mfqev2的训练集相比ldv2.0的训练集差异大吗？我如果继续做这个方向，您建议在哪个数据集上做？

**Comment by ryanxingql** [comment]
您好，是的，为了方便，模型都是在RGB上训练的，然后在Y上没有训直接测

我也很好奇为什么STDF结果不理想；我怀疑是mmediitng的DCN和之前我的STDF仓库的DCN有区别。具体我还没来得及深究。

MFQEv2数据集和LDVv2数据集差别较大；后者规模和分辨率都要大得多。如果为了打比赛，后者更好；但如果是为了发论文，前者更好，因为方便对比（MFQEv2论文里的结果您就不用重新跑了，可以直接用了）。而且数据库太大，不利于你的模型收敛和算法迭代，耗时太长。

**Comment by woaicv** [comment]
好的，非常感谢您的回复。我准备先在mfqe2.0上跑下basicsr++看看效果。主要basicvsr++代码里没公布训练细节，不知道我这个跑起来结果会怎么样。

**Comment by ryanxingql** [comment]
您是说用basicvsr++增强吗？这里有[配置文件](https://github.com/ryanxingql/powervqe/blob/main/mmediting/configs/restorers/basicvsr_plusplus/ldv_v2_4gpus.py)，是您需要的训练细节吗？

**Comment by woaicv** [comment]
是的，用basicsr++做视频增强。您之前跟我说过basicvsr++是不错的baseline，我准备在上面改改。我这试着训练一下，非常感谢！

**Comment by ryanxingql** [comment]
> 您好，非常感谢您的工作！我想请教下你们在竞赛里是在rgb上训练视频的吗？我看到您这边给的两个结果一个是Y-PSNR，一个是RGB-psnr（这个是mfqev2的测试集），这两个结果都是在rgb上训练然后在y或rgb通道上测的吗？为什么stdf的表现这么差，甚至都不如mfqev2（相比于之前在y通道训练 y通道测试）。mfqev2的训练集相比ldv2.0的训练集差异大吗？我如果继续做这个方向，您建议在哪个数据集上做？

您好
我最近发现代码有bug，具体是dcn的`deform_groups`参数设置写成了`deformable_groups`：
https://github.com/ryanxingql/powervqe/commit/c015b17ee35a04fa7fb1cd4334959de46de91b05
奇怪的是，之前跑并没有报错。
我刚刚修正，并且正在重新跑模型。如果有更新，我会通知您。

**Comment by woaicv** [comment]
好的，非常感谢🙏  有个问题想请教您下，我现在在用mfqev2的数据集来训练basicvsr++，我按照您在stdf中的做法把数据集弄成lmdb，我感觉这边是在108个训练集随机取的，感觉会不会样本不平衡的现象会减轻些，所以我没有截取前300帧，想多利用些样本，不知道这样做合不合理。我现在遇到了一个bug就是mfqev2的训练集存在图片大小 小于256的情况，而您在四倍下采计算光流那里声明了必须大于等于64，现在不知道这里应该怎么处理。

**Comment by ryanxingql** [comment]
> 好的，非常感谢🙏 有个问题想请教您下，我现在在用mfqev2的数据集来训练basicvsr++，我按照您在stdf中的做法把数据集弄成lmdb，我感觉这边是在108个训练集随机取的，感觉会不会样本不平衡的现象会减轻些，所以我没有截取前300帧，想多利用些样本，不知道这样做合不合理。我现在遇到了一个bug就是mfqev2的训练集存在图片大小 小于256的情况，而您在四倍下采计算光流那里声明了必须大于等于64，现在不知道这里应该怎么处理。

1. 关于样本平衡，您可以考虑3个维度：分辨率，帧数，帧间相似度。打比赛的时候会尽可能多考虑这些因素，但一般情况下不需要太考虑，因为我们要首先保证训练样本数量。MFQEv2训练集相对比较小，我建议您可以把所有patch用上。
2. 图像本身边长小于patch size了？那可能没别的办法了，只能在lmdb或者训练集中剔除掉不合格的视频帧。

**Comment by woaicv** [comment]
但是test_18中的四个测试集的高度也是小于256的。这几个的高度都是240![image](https://user-images.githubusercontent.com/90394190/178658025-f90eeb9a-da33-4d45-980b-a42f48adf7bc.png)

**Comment by ryanxingql** [comment]
> 但是test_18中的四个测试集的高度也是小于256的。这几个的高度都是240![image](https://user-images.githubusercontent.com/90394190/178658025-f90eeb9a-da33-4d45-980b-a42f48adf7bc.png)

您可以看下我代码的处理：
https://github.com/ryanxingql/powervqe#61-special-cases

主要是在这里：
https://github.com/ryanxingql/powervqe/blob/fc68391da43b6c2dda1edc9febeb867485ee596f/mmediting/mmedit/apis/restoration_video_inference.py#L243

训练就不必做这种处理了。

**Comment by woaicv** [comment]
好的，非常感谢，我这试下

**Comment by woaicv** [comment]
您好，我目前用双卡3090跑basicvsr++，但是这个训练好慢。您当时用v100训练这个模型也很慢是嘛？我怕我哪里弄错了。

![image](https://user-images.githubusercontent.com/90394190/178670305-9a085455-7be5-4944-807b-acc54b7f0da1.png)

**Comment by ryanxingql** [comment]
> 您好，我目前用双卡3090跑basicvsr++，但是这个训练好慢。您当时用v100训练这个模型也很慢是嘛？我怕我哪里弄错了。
> 
> ![image](https://user-images.githubusercontent.com/90394190/178670305-9a085455-7be5-4944-807b-acc54b7f0da1.png)

Basic是这样的。因为iter总数是固定的，所以训练时间不会因为训练集改变而改变。
注意我的配置文件应该是4卡的，你需要改samples_per_gpu=2参数。
原版Basic是在8卡跑的，都需要跑5-7天。

**Comment by woaicv** [comment]
是的，我有注意到您的配置文件是4卡的，每个卡的batch是2，总batch为8，但是我目前3090两张卡，每张卡的显存是24g，目前我只能把单张的batch设为3，总batch为6，目前只能暂时这样，相比您batch-size 8是不是会影响精度。我能不能减少下iter数量，感觉11天有点接受不了，您有跑过mfqev2数据集嘛，减小iter是不是会对精度影响很大？

**Comment by ryanxingql** [comment]
> 是的，我有注意到您的配置文件是4卡的，每个卡的batch是2，总batch为8，但是我目前3090两张卡，每张卡的显存是24g，目前我只能把单张的batch设为3，总batch为6，目前只能暂时这样，相比您batch-size 8是不是会影响精度。我能不能减少下iter数量，感觉11天有点接受不了，您有跑过mfqev2数据集嘛，减小iter是不是会对精度影响很大？

我没试过在mfqev2上跑basicvsr++；我只在ldv跑过，因为我想以后有同学跑竞赛会用到这个预训练模型。
我不确定是否会影响，这需要根据您的tensorboard的val情况作评估。如果提前饱和了，就可以提前终止。
basicvsr++已经是非常大的模型了，这个训练时长还是很合理的……我也很无奈哈哈

**Comment by woaicv** [comment]
好的，很感谢。那我先训练着看看

**Comment by woaicv** [comment]
您好，我遇到了很奇怪的问题，我在测试的时候会一直卡死，现在只能测试416*240的图片，如果加载480*832的图片就会卡死，尽管我将maxlen设置为30还是会卡死，我现在不知道是什么原因，按理说2张24g的卡不至于这样一直卡死，是我哪里没注意嘛。如果您能解答非常感谢

**Comment by ryanxingql** [comment]
是basicvsr++吗？你可以注意下内存；因为程序用内存换显存，否则显存会不足

**Comment by WilliammmZ** [comment]
你好，想问一下这里提供的basicvsrPP在MFQEv2的结果，是利用在LDVv2上预训练的模型测试的对吗？因为我自己跑了一下它在MFQEv2上的结果，稍微有些差别。

**Comment by woaicv** [comment]
> 你好，想问一下这里提供的basicvsrPP在MFQEv2的结果，是利用在LDVv2上预训练的模型测试的对吗？因为我自己跑了一下它在MFQEv2上的结果，稍微有些差别。

请问一下你在mfqev2.0上测的结果是多少？

**Comment by ryanxingql** [comment]
> 你好，想问一下这里提供的basicvsrPP在MFQEv2的结果，是利用在LDVv2上预训练的模型测试的对吗？因为我自己跑了一下它在MFQEv2上的结果，稍微有些差别。

对，我确认一下，

1. 测试代码是：https://github.com/ryanxingql/powervqe#62-special-case-of-basicvsr-over-the-mfqev2-dataset
2. 计算psnr代码是：https://github.com/ryanxingql/powervqe#64-psnr-calculation

对吗？注意，`cal_y_psnr.py`有变化，注意用最新版代码。和旧代码的区别：旧代码用了opencv的bgr2ycbcr，和mmediting的bgr2ycbcr是不一样的，因此y-psnr结果有问题。最新代码更正了这个问题，统一使用mmediting的bgr2ycbcr。

**Comment by WilliammmZ** [comment]
> 
感谢提醒~ 我自己也使用的mmediting的框架。

**Comment by WilliammmZ** [comment]
> > 你好，想问一下这里提供的basicvsrPP在MFQEv2的结果，是利用在LDVv2上预训练的模型测试的对吗？因为我自己跑了一下它在MFQEv2上的结果，稍微有些差别。
> 
> 请问一下你在mfqev2.0上测的结果是多少？

因为内存只有256G 2k视频和1080p视频是分别切50帧和100帧测试的，会有一定掉点。 整体的Δpsnr在0.96左右。

**Comment by WilliammmZ** [comment]
> > 你好，想问一下这里提供的basicvsrPP在MFQEv2的结果，是利用在LDVv2上预训练的模型测试的对吗？因为我自己跑了一下它在MFQEv2上的结果，稍微有些差别。
> 
> 对，我确认一下，
> 
> 1. 测试代码是：https://github.com/ryanxingql/powervqe#62-special-case-of-basicvsr-over-the-mfqev2-dataset
> 2. 计算psnr代码是：https://github.com/ryanxingql/powervqe#64-psnr-calculation
> 
> 对吗？注意，`cal_y_psnr.py`有变化，注意用最新版代码。和旧代码的区别：旧代码用了opencv的bgr2ycbcr，和mmediting的bgr2ycbcr是不一样的，因此y-psnr结果有问题。最新代码更正了这个问题，统一使用mmediting的bgr2ycbcr。

感谢提醒~
