### ISSUE TITLE
mmediting submodule or subtree

### ISSUE THREAD

**Issue by itsagoodbrain** [ryanxingql/powervqe#5]
Can we get the mmediting directory as a subtree or submodule. I'm more familiar with submodules and I partially tried to do this but the merge wasn't clean even with your fork. If you're going to allow or suggest potential updates to mmediting, I would recommend keeping changes needed for this repo in a branch of your fork. You can then simply make a submodule that tracks that branch. It is then trivial for end users to pull changes from the main mmediting repo.

**Comment by ryanxingql** [comment]
Thank you for your suggestion, I love that ^ ^ I will do this in PowerVQE v2 update later.
