### ISSUE TITLE
当我使用pycharm进行远程调试时，程序找不到路径下的数据集

### ISSUE THREAD

**Issue by wgp666** [ryanxingql/powervqe#7]
报错如下：
ValueError: You may use too small dataset and our distributed sampler cannot pad your dataset correctly. We highly recommend you to use fewer GPUs to finish your work

**Comment by ryanxingql** [comment]
您好

1. 邀请您使用最新的仓库：https://github.com/ryanxingql/powerqe
2. 您是否将数据集软链接至 "powerqe/data"？

**Comment by wgp666** [comment]
我已将数据集软链接至"powerqe/data"，当我使用XShell远程连接运行程序的时候是没有问题的，但是使用pycharm远程调试时就会出现上面的问题。

**Comment by ryanxingql** [comment]
我猜测两种情况下 python 路径不同；而 "data" 是相对路径，因此 pycharm 调试时绝对路径是错的，导致问题。

我没有使用过 pycharm 调试，请您根据这个线索再 debug 下。BTW 欢迎使用最新的 [PowerQE](https://github.com/ryanxingql/powerqe) 仓库。

**Comment by wgp666** [comment]
好的，谢谢您的解答！
