### ISSUE TITLE
关于训练速度问题

### ISSUE THREAD

**Issue by wgp666** [ryanxingql/powervqe#8]
你好，我这有一个问题就是训练basicvsr++的时候当程序在5000次迭代验证后，出现训练速度变慢的情况，变慢了很多。在验证前的训练速度大概是2分钟左右100次迭代，但是验证结束后模型训练速度变得慢了很多。大概100次迭代要3个小时左右。请问您知道原因是什么吗。以下是我的训练日志。
[20230608_115628.log](https://github.com/ryanxingql/powervqe/files/13793389/20230608_115628.log)

**Comment by ryanxingql** [comment]
您好抱歉那么晚回复您。根据您的日志，时间慢是由于 data time 猛增导致的。建议您调整 num workers、gpu 等参数。
